### ISSUE TITLE
Varnish 4.0 incompatibility

### ISSUE THREAD

**Issue by gi11es** [varnish/libvmod-xkey#4]
This vmod doesn't compile on 4.0. Either it should be made compatible with 4.0, or its minimum requirement of 4.1 should be made explicit. Right now the build fails ungracefully: https://gist.github.com/gi11es/5b55347a9888596fda74

**Comment by lkarsten** [comment]
Hi. This is on purpose.

Please upgrade to the latest version of Varnish Cache.

**Comment by gi11es** [comment]
Did you read the body of my issue? I'm fully aware that the current code is incompatible. But this version dependency isn't documented anywhere. It's not even mentioned in the README. Hence there is no way to know that this is intentional.

**Comment by lkarsten** [comment]
Hi.
You're right, it isn't very well explained. I've added a note of it now.

Thanks for bringing it to our attention.

**Comment by fgsch** [comment]
@lkarsten If we want to restrict it to >= 4.1 and trunk I have a patch. 
Alternatively I could check if the define is present.

**Comment by lkarsten** [comment]
Adding a configure check sounds good.

We should apply it to vmod-example first, probably?

**Comment by fgsch** [comment]
But wouldn't this restrict the example vmod unnecessarily?  My understanding of the example vmod is that it should be generic.  It should be the author who decides what the minimum requirements are.

**Comment by lkarsten** [comment]
I don't see an issue here; this is just another versioning check, like sufficiently new pcre or libmemcache.
Add a comment on the preceeding line saying how to disable it.

**Comment by fgsch** [comment]
If we were to add it I think it'd make more sense to have it disabled by default.
People are not based their project in Varnish (pcre) or a specific vmod (memcached).

That said I don't particularly mind as long as we address the requirement in here.

**Comment by dridi** [comment]
Closing, the VMOD now lives in [varnish-modules](https://github.com/varnish/varnish-modules).
